### ISSUE TITLE
Optimizar la carga de olores en el mapa

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/odourCollect_2.0#106]
Creo que sería una buena idea crear un controlador con sus edpoints correspondientes que cargue de forma específica los datos que necesita front sobre las observaciones para optimizar el rendimiento y comodidad.

De momento crear un controlador que devuelva de todos los olores estos datos:
- id
- user_id
- lat
- long
- color?

**Comment by CarlosMillanSfC** [comment]
Claro, de esto me di cuenta que cuando suba ese controlador, con esas rutas, será accesible desde la app en producción y puede generar dudas. Voy a crear un middleware para que pueda estar esa ruta en el fichero de rutas pero solo accesible desde local.

**Comment by CarlosMillanSfC** [comment]
Ya he subido un endpoint y mejora mucho los tiempos.
{{URL_DEV}}/api/map
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/4b2b45de-e7ab-4b78-9655-0ab1bcb468ab)
Tiene los mismos filtros y funcionalidades que {{URL_DEV}}/api/observations para probar y tal.

Y también claro, si vamos a hacer que el color dependa del grado de molestia y la matriz tiene en cuenta tono hedónico e intensidad y no deberían poder modificarse esos campos veo mejor que calcule el grado de molestia cuando se suba el olor.
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/4141b96e-7533-45be-a455-931d262c68d6)

Voy a crear una issue para incorporar este comportamiento

**Comment by TomasTubertSFC** [comment]
@CarlosMillanSfC Estaría bueno hacer una reunión y que me expliques 5' como está. Por lo que entiendo, el endpoint de mapa ahora tiene también los filtros?

**Comment by CarlosMillanSfC** [comment]
#130 Ya he mergeado en develop la funcionalidad de que devuelva el color, lo hace según la matriz de grado de molestia, devuelve un conjunto de objetos tal que así:
        {
            "id": 1,
            "user_id": 10,
            "latitude": "41.38990",
            "longitude": "2.17520",
            "color": 3
        }
La cosa es que según he podido ver, en la escala de intensidad que tenemos hay 7 valores y en esa matriz se tienen en cuenta 6. Para que no haya colores "huérfanos" les he puesto a esos que devuelva 8 como valor fallback, creo que solo hay 2236 (soloxD). Ya veremos qué hacer para eso pero lo hablaré con @JohanaSfC. 

Esto solo está en el endpoint de api/map. Cualquier cosa seguimos hablando por aquí @TomasTubertSFC

**Comment by TomasTubertSFC** [comment]
@CarlosMillanSfC Me he dado cuenta que también necesitaría que cuando se crea una observación en el endpoint POST /api/observations, el color de la matriz como dato.

**Comment by CarlosMillanSfC** [comment]
cierro de momento esta issue porque ya está implementado en producción el endpoint de /map y parece funcionar. Futuras optimizaciones ya partiran desde ahí.
