### ISSUE TITLE
Endpoint para descargar los olores del usuario loggeado

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/odourCollect_2.0#107]
Como no hay especificaciones más allá de la funcionalidad que se descarguen los datos en formato CSV o el más cómodo.

**Comment by SysAdminSfC** [comment]
puedes añadir los fechas porfa? start date y end date

**Comment by SysAdminSfC** [comment]
@CarlosMillanSfC puedes añadir start date y end date a este issue porfa?

**Comment by CarlosMillanSfC** [comment]
cierro esta issue porque se está tratando mejor en:

> Stand By: #171
