### ISSUE TITLE
Simplificar al máximo los mensajes de error de laravel

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/odourCollect_2.0#109]
los 422 deben ser lo más corto y simples posibles ya que gestionaremos los textos desde front.

**Comment by almenarasfc** [comment]
Ok!

**Comment by CarlosMillanSfC** [comment]
Cierro esta issue porque ya @almenarasfc lleva el fichero y los mensajes de error, los mensajes de error de laravel ya están simplificados
