### ISSUE TITLE
FILTROS DEL MAPA

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/odourCollect_2.0#114]
Faltaría comprobar los endpoints de:

-> Distancia: //
-> Hora: http://odourcollect.local/api/observations/?include=odourSubType.odourType,user.userable&filter[createdTodayBetween]=13:00,23:00

**Comment by CarlosMillanSfC** [comment]
He subido este cambio, #122 y podemos de momento hacer que me mandes por la url, la lat/long del usuario y la distancia, queda medio feo estilo así:
(casi seguro que el is_inside es en metros)
{{URL_DEV}}/api/observations?is_inside=5000,latitude=41.3776,longitude=2.1530

No he podido testearlo en si, pero podemos probar a ver si suena la flauta @TomasTubertSFC

**Comment by CarlosMillanSfC** [comment]
Vas jugando con el is_inside y van saliendo resultados diferentes, se podría ver de incluso pintar un círculo o así, no sé si es muy complicado @TomasTubertSFC 
http://odourcollect.local/api/map?is_inside=1000&latitude=41.3776&longitude=2.1530

**Comment by TomasTubertSFC** [comment]
Me acabo de dar cuenta que los filtros, van así:
 filter[is_inside]=7000
Queda raro si el de is_inside va sin corchetes y sin filter deltante no?
Quedaría como filter[type]=[1,2]&is_inside=1000
Está bien así?

**Comment by CarlosMillanSfC** [comment]
Está bien, es que el filtro de is_inside es diferente a los otros ya que este se aplica con el resultado de la query.
Como hablamos da igual el orden en que se especifiquen los parámetros, tanto si el "is_inside" va al principio o al final

**Comment by TomasTubertSFC** [comment]
La url quedaría así:
map?filter[type]=1,2&filter[intensity]=1,6?is_inside=7000,latitude=41.371064,longitude=2.1548569
