### ISSUE TITLE
Crear lógica para agregar color según el grado de molestia

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/odourCollect_2.0#123]
@TomasTubertSFC 
Ya he subido un endpoint y mejora mucho los tiempos.
{{URL_DEV}}/api/map
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/4b2b45de-e7ab-4b78-9655-0ab1bcb468ab)
Tiene los mismos filtros y funcionalidades que {{URL_DEV}}/api/observations para probar y tal.

Y también claro, si vamos a hacer que el color dependa del grado de molestia y la matriz tiene en cuenta tono hedónico e intensidad y no deberían poder modificarse esos campos veo mejor que calcule el grado de molestia cuando se suba el olor.
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/4141b96e-7533-45be-a455-931d262c68d6)

Voy a crear una issue para incorporar este comportamiento

_Originally posted by @CarlosMillanSfC in https://github.com/ScienceForChange/odourCollect_2.0/issues/106#issuecomment-1921945201_

**Comment by TomasTubertSFC** [comment]
![Captura de pantalla 2024-02-09 112250](https://github.com/ScienceForChange/odourCollect_2.0/assets/144031996/f01b8175-c12a-49a0-8248-744e3a8f05fa)

**Comment by TomasTubertSFC** [comment]
![Captura de pantalla 2024-02-09 112706](https://github.com/ScienceForChange/odourCollect_2.0/assets/144031996/6d581f6e-0e11-46b0-abb2-5876a5f41094)
@CarlosMillanSfC Depende de que grado de matriz me envíes se mostrará un color diferente. El 0 es blanco y el 7 el rojo de arriba.

**Comment by CarlosMillanSfC** [comment]
puesto ya que contemple la posibilidad de una intensidad de 0 (no perceptible) y de 0 cualquier combinación de ese valor con otro de tono hedónico.

He dejado que cuando se intente una combinación no contemplada (por ejemplo -10 y 99) devuelva -1 dando a entender que hay algo mal con esa observación para calcular su grado de molestia y hay que mirarlo
#183

**Comment by CarlosMillanSfC** [comment]
Cierro pero creo una issue para crear un script que agregue a las observaciones el color ya calculado (de momento se calcula al vuelo)
