### ISSUE TITLE
Script perfil de usuario

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#133]
todos los usuarios registrados deben tener perfil en la tabla profile_citizens

**Comment by CarlosMillanSfC** [comment]
Haremos de crear un perfil vacío (dummy) para los usuarios porque pasaba que algunos usuarios al migrar la bbdd antigua tenían un perfil que no era coherente (estilo su email era: carlos@gmail.com pero su nombre Eustaquio) o ni siquiera un perfil asociado y no sé hasta qué punto eran nombres inventados o realmente salió mal la migración. 
Esto es un problema porque datos básicos de los usuarios se pueden ver desde distintos puntos de la app, yo haría de dejarlos vacíos como digo y que un modal o pantalla le pida que rellene de nuevo esos datos para poder utilizar la app con su cuenta de correo.
Cómo lo veis? @OtariOboladzeSfC @almenarasfc @TomasTubertSFC ?

**Comment by OtariOboladzeSfC** [comment]
>  que rellene de nuevo esos datos para poder utilizar la app con su cuenta de correo

cuales son los datos obligatorios para los usuarios?

**Comment by almenarasfc** [comment]
Lo malo es que no hay opción en la app de editar estos datos

**Comment by CarlosMillanSfC** [comment]
Habría entonces de crear una pantalla para ello o así, no? confirmamos con Johana si eso el estilo y le comentamos la casuística, si quieres yo o tú @almenarasfc

**Comment by almenarasfc** [comment]
Sí, que nos confirmen @OtariOboladzeSfC y/o @JohanaSfC  como lo quieren resolver y lo hablamos.

**Comment by JohanaSfC** [comment]
El objetivo es tener una base de datos unificada de todos los usuarios y teniendo en cuenta que vamos a migrar usuarios antiguos de la aplicación a la nueva versión. 
Solución: a los usuarios antiguos tenemos, una vez iniciada sesión en la nueva app, aparecerá una pantalla donde se les solicitará actualizar los datos sobre todo los campos obligatorios: name, birth_year, email, gender, password.
La pantalla aparecerá una sola vez.

**Comment by CarlosMillanSfC** [comment]
> @JohanaSfC otra solucion sera no poner name, birth_year y gender como campos obligatorios, porque como aparecera una pantalla: donde? en el perfil? al principio? cuando? cada vez tenemos que hacer eso o solo una vez para cada usuario? necsitamos extra API por eso?

estas preguntas házmelas a mi oto, si @JohanaSfC está aceptando una solución mía esas preguntas te las puedo resolver yo.
- donde? -> al principio
- en el perfil? -> no
- al principio? -> si
- cuando? -> cuando haga login
- cada vez tenemos que hacer eso o solo una vez para cada usuario? -> una vez para usuario sin el perfil completado (los antiguos)
- necsitamos extra API por eso? -> sí, ya lo he creado y es: {{URL_PROD}}/api/users/u/{user_id}
que solo será accesible desde esa pantalla que se mostrará en la comprobación del principio después de hacer login.

Solo falta:
- [] crear modal en front
- [] crear pantalla para editar nombre, género y año de nacimiento.
- [] llamada al endpoint {{URL_PROD}}/api/users/u/{user_id}

Te la dejo asignada a ti @almenarasfc y cuando lo tengas la cierras porfa

**Comment by almenarasfc** [comment]
@JohanaSfC @OtariOboladzeSfC | En este mismo sentido, si al cambiar la aplicación han cambiado las bases legales, ¿no deberían los usuarios antiguos aceptar las nuevas bases legales antes de continuar?

**Comment by almenarasfc** [comment]
@JohanaSfC he creado este modal para terminar de completar el perfil de usuario, aparecerá siempre que el usuario este incompleto y no te dejará hacer nada hasta que completes tu perfil:
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/916bc524-ed0a-4774-8e15-f791a7df8f82)
