### ISSUE TITLE
Cambio en el nombre de las tipologías de olores

### ISSUE THREAD

**Issue by TomasTubertSFC** [ScienceForChange/odourCollect_2.0#134]
@CarlosMillanSfC me he dado cuenta que el endpoint de /observations/related-data devuelve unos tipos distintos:
![Captura de pantalla 2024-02-05 072335](https://github.com/ScienceForChange/odourCollect_2.0/assets/144031996/c892b3ef-84b6-48a3-95df-bfdb53370ef3)

Me gustaría que me informarais @JohanaSfC para saber como agrupar o que icono poner o que opción mostrar. Por ejemplo:
- En el formulario, Other y No odour, se ha de mostrar como opción para crear una observación?
- No odour y Other, son opciones para elegir como filtros?
- De ser que si, que color e icono utilizamos?

**Comment by CarlosMillanSfC** [comment]
Respondiendo a tus dudas:
- Sobre no odour debe ser con una línea "fina" sin icono. Sobre other no tenemos el icono correspondiente por lo que tenemos que pedirlo.
- Sí, como cualquier otro tipo
- Sobre icono para other no tenemos, podemos buscar nosotros y proponer, y color siguiendo la gama de colores que tenemos elijamos.

fdo/@JohanaSfC

**Comment by CarlosMillanSfC** [comment]
Entiendo que si no hay más dudas se da por cerrada esta issue
