### ISSUE TITLE
Datos de usuario incompletos

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#144]
Necesitamos definir que hacer con los usuarios que ahora tendrán sus datos de perfil incompletos

**Comment by CarlosMillanSfC** [comment]
Lo que pasaba es que muchos usuarios (antiguos) tenían un perfil incompleto, mal asociado o directamente inexistente por lo que hemos decidido desasignar los perfiles y que a cada usuario antiguo al entrar en la app le salte un modal diciendo que tiene que "completar su datos". 

Los datos que se tienen que rellenar son: 
- name
- gender
- birth_year 

Se hace a través del endpoint: 
[PATCH] 
{{URL_DEV}}/api/users/2609 
x-www-form-urlencoded
Body:
name:Carlos
gender:hombre
birth_year:1993
Haders:
Accept:application/json
X-XSRF-TOKEN:{{XSRF-COOKIE}}
Referer:odourcollect.local

Al final es editar el endpoint "update" del usuario enfocado solo al perfil ya que para cambiar la contraseña hay un endpoint específico, para el correo dijimos que no se pudiera y para el avatar crearé uno específico. 
Salvo lo del avatar está ya todo subido a develop (#152)  @almenarasfc  te aviso cuando también esté el endpoint del avatar.
