### ISSUE TITLE
SSL on odourcollect.cloud

### ISSUE THREAD

**Issue by SysAdminSfC** [ScienceForChange/odourCollect_2.0#204]

**Comment by CarlosMillanSfC** [comment]
Ya hecho. Para renovar los certificados tanto en odour como en sound he dejado configurado para que sea solo entrar y lanzar este comando: 
`docker compose -f /usr/src/docker-compose.prod.yml run --rm certbot --dry-run renew`

Si da que todo bien es lanzarlo sin el flag de --dry-run y renueva el certificado.

Voy a crear una issue aparte para crear un cron que lo ejecute cada cierto tiempo.
