### ISSUE TITLE
Tipología de olores, tipo e intensidad idioma español.

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#212]
La tipología de olores sigue estando en inglés, cuando ya he pasado los documentos en español.
Hacer el cambio, o tomar la decisión si eso se hace en el back o front. @CarlosMillanSfC @TomasTubertSFC @OtariOboladzeSfC 

<img width="150" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/2c15b007-80a1-4cde-a15c-419877db1422">

**Comment by JohanaSfC** [comment]
Lo mismo sucede con el tipo y subtipo. 

<img width="134" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/5034934b-c0fa-4b13-921e-ffdd46f11f7a">

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC has podido o vas a poder ponerte con esto o lo hago yo? que si no me equivoco me dijiste que lo ibas a hacer tú pero puede que no.

**Comment by SysAdminSfC** [comment]
@CarlosMillanSfC can you do it pls? it will be seeders + actual DB modification

**Comment by JohanaSfC** [comment]
La información de las tipologias en español esta en el repositorio ["OdourCollect 2.0 frontend issue #264"](https://github.com/ScienceForChange/OdourCollect_2.0_frontend/issues/264)

**Comment by CarlosMillanSfC** [comment]
Probando la versión en local vemos que algunos nombres largos rompen un poco pero los separaremos en dos líneas, en concreto el subtipo: Estación de tratamiento de aguas residuales y el tipo Aguas residuales y residuos pero @almenarasfc los separará en dos líneas y ya.

Porfa, cuando lo tengas mergea a master y tiramos el php artisan migrate:refresh --seed en el servidor para que coja los nombres en español.
