### ISSUE TITLE
Header mis olores/ todos los olores

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#214]
Aparece el header de mis olores/todos los olores en la pantalla de mi perfil. 
También el icono de buscar mi localización y la leyenda del mapa.

@OtariOboladzeSfC 

<img width="197" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/9b5033f9-e935-4f7c-83f6-544d214869f8">

**Comment by OtariOboladzeSfC** [comment]
es para @almenarasfc o para @TomasTubertSFC ?

**Comment by TomasTubertSFC** [comment]
Esto no funciona por que .cloud no está actualizado aun.

**Comment by CarlosMillanSfC** [comment]
Pero lo subiste ya a develop? si es así la cierro.
