### ISSUE TITLE
Pantalla "mi perfil" no sigue el diseño del figma

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#215]
Esta pantalla tiene errores en los colores. @OtariOboladzeSfC @almenarasfc 

<img width="160" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/5f8d2769-fddf-429b-91f1-ce9967e5a593">

**Comment by almenarasfc** [comment]
@JohanaSfC 
Esto se da por un error de back, el usuario no tiene el perfil completo

@CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
bueno, es ver qué nos responden aquí:
https://github.com/ScienceForChange/odourCollect_2.0/issues/133#issuecomment-1952650412

Yo propongo crear como un endpoint que deje actualizar los campos name, gender, birth_year que solo se pueda atacar desde una pantalla que solo se de acceso si te falta alguno de ellos (controlado desde el front) Y una vez relleno no deje más y solo después solo desde el update normal.

Dejo hecho el endpoint, es: {{URL_DEV}}/api/users/u/{user_id}

**Comment by OtariOboladzeSfC** [comment]
> Yo propongo crear como un endpoint que deje actualizar los campos name, gender, birth_year que solo se pueda atacar desde una pantalla que solo se de acceso si te falta alguno de ellos (controlado desde el front) Y una vez relleno no deje más y solo después solo desde el update normal.

**Comment by OtariOboladzeSfC** [comment]
> Yo propongo crear como un endpoint que deje actualizar los campos name, gender, birth_year que solo se pueda atacar desde una pantalla que solo se de acceso si te falta alguno de ellos (controlado desde el front) Y una vez relleno no deje más y solo después solo desde el update normal.

![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/116548840/da86f8cb-7269-45c5-86c9-f631c98e46aa)

**Comment by CarlosMillanSfC** [comment]
Solucionado, he creado perfiles vacíos para que así ningún usuario esté huérfano de perfil.
Los perfiles están asociados a los usuarios pero están sin nombre, géro y año de nacimiento. Mantengo lo de crear las pantallas para que se pida que lo rellenen @almenarasfc @TomasTubertSFC 
En la daily lo vemos
