### ISSUE TITLE
Funcionalidad usuario entrenado

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#216]
@OtariOboladzeSfC  Confirmar que se entiende el funcionamiento de la funcionalidad usuario entrenado. 
No debe aparecer este texto de usuario entrenado y el icono de más información. Si yo como usuario no soy usuaria entrenada. 

<img width="145" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/018db77d-5671-4ebe-b349-db7349938d0e">

**Comment by CarlosMillanSfC** [comment]
se puede cambiar el atributo is_trained desde update(): Observable<Object> (mandando el campo is_trained a 1)

**Comment by OtariOboladzeSfC** [comment]
cual es el estado de este issue? @almenarasfc

**Comment by CarlosMillanSfC** [comment]
@JohanaSfC 
Asigno esta tarea a @almenarasfc y que te explique él, en principio sí funciona pero creo que tenéis una visión diferente, por favor, dejad aquí la que se decida.

**Comment by OtariOboladzeSfC** [comment]
algun update @almenarasfc ?

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC Entiendo que esta issue es la duda que yo planteé hace algunas semanas. El texto "Usuario entrenado" (que sirve para ver la información de qué es un usuario entrenado) aparece tal cual para todos los usuarios. Esto puede generar confusión, ya que puede dar a entender que tu ya has sido entrenado. Propuse cambiar esa frase por "¿Qué es un usuario entrenado?".
