### ISSUE TITLE
Gamificación

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#217]
@OtariOboladzeSfC @almenarasfc 

En la pantalla de mis premios, a los usuarios que no tienen premios. Les debe aparecer un texto que diga "lamentablemente aún no tienes ninguna insignia. Te gustaría saber como obtenerlas" Link a la pantalla de mis insignias. 

<img width="156" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/989fb85e-acad-4fea-b9b5-92a4937f2c3d">

Esta pantalla está desactualizada, debe aparecer las imágenes de las insignias. 

<img width="143" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/c27da903-1b35-431f-afac-bb6a1b8327fd">

**Comment by almenarasfc** [comment]
@JohanaSfC 
que no aparezcan los trofeos tiene que ve con este error: [issue](https://github.com/ScienceForChange/odourCollect_2.0/issues/133#issuecomment-1946322777)

Cuando esté actualizado el servidor los trofeos aparecerán en gris lo NO conseguidos y el color los que hayas logrado.

**Comment by almenarasfc** [comment]
@JohanaSfC 
Corregido el modal:
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/d4155f64-9083-4612-ad28-e3cc0d3a0bf1)
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/fef91089-57e8-4525-9af4-4b8ddd7c6dab)
