### ISSUE TITLE
translate text fields on database and seeders from EN to ES

### ISSUE THREAD

**Issue by SysAdminSfC** [ScienceForChange/odourCollect_2.0#229]

**Comment by SysAdminSfC** [comment]
@CarlosMillanSfC  can you add start and end dates pls?

**Comment by CarlosMillanSfC** [comment]
aquí tienes las traducciones @OtariOboladzeSfC 
https://docs.google.com/spreadsheets/d/12u3ql6xEyxAmIWOaGWVX-9kJwGpD0BQf_gLmkLfb9Gk/edit#gid=0

**Comment by CarlosMillanSfC** [comment]
There is no field for that.
Start Today 
End Today
