### ISSUE TITLE
Verificar que el link de cambio de contraseña tiene duración de 60 minutos. 

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#239]
@SysAdminSfC @CarlosMillanSfC puedes verificar que el link que llega al correo cuando quieres cambiar la contraseña tiene una duración de 60 minutos. 
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/4df13a7c-6ca8-4186-914b-7f63c72991f4)

**Comment by CarlosMillanSfC** [comment]
Confirmo que ese link después de más de 1 hora no funciona ya. Cierro y bien visto @JohanaSfC porque no lo había comprobado al 100%

**Comment by CarlosMillanSfC** [comment]
@almenarasfc sí que es cierto que cuando intentas cambiar la contraseña te abre ese link y todo y al poner otra se queda pensando eternamente pero porque ha recibido un:
```
{
    "message": "This password reset token is invalid.",
    "errors": {
        "email": [
            "This password reset token is invalid."
        ]
    }
}
```
Deberíamos controlarlo aunque como dices esto debería ser desde la app y no una página web :/

**Comment by OtariOboladzeSfC** [comment]
entonces que queda en este issue para cerrarla de front/back?  @almenarasfc @CarlosMillanSfC

**Comment by almenarasfc** [comment]
@OtariOboladzeSfC Resolveré esto por ahora en front, pero hasta que no tengamos la App en iOS no podremos saber si podemos abrir esa pantalla en la app desde el correo.

**Comment by almenarasfc** [comment]
En caso de caducidad del token de recuperación de contraseña, ahora aparece un modal advirtiendo del error y sugiriendo volver a solicitar el cambio de contraseña al usuario.



![Image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/f9f5328e-2d75-494f-8b62-44de687e8922)
