### ISSUE TITLE
Sistema de comunicación y aceptación de nuevos términos y bases legales.

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#249]
Cuando se renueven las bases legales y sea necesario volver a aceptarlas deberá aparecer un modal que impida continuar utilizando la app hasta aceptarlas o bien desloguearse.

**Comment by almenarasfc** [comment]
@CarlosMillanSfC 

tenemos algún endpoint para esto?

**Comment by CarlosMillanSfC** [comment]
Saludos @almenarasfc .

No, actualmente no hay un "endpoint" mágico que te diga si el usuario  debe o no aceptar unas nuevas bases legales puesto que es una funcionalidad que, por como está planteada, depende del dashboard/admin y aún no está desarrollada. Según tengo entendido cuando se actualice alguna política de privacidad, o así, se comparará la fecha de creación de esa nueva política con la fecha que tiene registrada el usuario cuando aceptó la política.

Tienes es que los usuarios tienen un campo asociado a su perfil que es: **_accepted_legal_at_** indicando cuándo han aceptado los términos y condiciones legales/éticos. 
Y te explico: los usuarios nuevos, los que se registren de aquí en adelante, tendrán ese campo con la propia fecha de creación ya que tendrán que aceptarlos para validar su registro pero lo usuarios antiguos no tienen ese campo relleno con una fecha. por lo que puedes comprobar rápido que deben aceptar una nueva y así hacerselo saber al propio usuario con un modal o lo que te plazca.

Un saludo y nos mantenemos en contacto.

**Comment by CarlosMillanSfC** [comment]
se trata en #247
