### ISSUE TITLE
[UX UI] ONBOARDING

### ISSUE THREAD

**Issue by CarlosMillanSfC** [ScienceForChange/odourCollect_2.0#253]
Hola, me incomoda mucho como usuario asiduo de la aplicación que cuando quiero enseño la app a amigos y familiares el apartado de "onboarding" no permite gestos para pasar de pantalla en pantalla.

Podríais considerar parte de vuestro tiempo para esta humilde tarea? Muchas gracias

**Comment by TomasTubertSFC** [comment]
Por supuesto que si amigo.

**Comment by CarlosMillanSfC** [comment]
@TomasTubertSFC 

![Observaciones_AMB](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/44bcc8d2-c90e-4a9d-8ca4-fa4f40c35d6a)

**Comment by CarlosMillanSfC** [comment]
Gracias a esa última PR puedo decir, sin temor a equivocarme:

Con este sencillo y emotivo acto doy por cerrada esta issue.

Gracias, de corazón, @TomasTubertSFC

**Comment by TomasTubertSFC** [comment]
Ahora ya vas a poder disfrutar de poder enseñar el magnífico trabajo en el onboarding, a tu gente
