### ISSUE TITLE
Bug al cambiar de avatar,

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#261]
Se produce un error al enviar el perfil de usuario para actualizar, unificar back y front en el nombre de las propiedades del modelo usuario.

@CarlosMillanSfC 

![Image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/d3ada9a7-f81f-40ff-865f-31860caf3540)

![Image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032518/0fd296af-137e-4664-961b-0f672938a028)

**Comment by OtariOboladzeSfC** [comment]
cual sera mas sencillo para modificar: front o el back? @almenarasfc @CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
solucionado, era un fallo mío en la validación de campos. Lo he corregido manteniendo la convención de tratar los json con camelCase.
esperaba recibir birth_year cuando debería haber sido birthYear
