### ISSUE TITLE
Filtros no actualizan correctamente (mapa)

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#297]
He filtrado primero por intensidad y después por he vuelto a los filtros y he filtrado por tipos. Me ha aparecido el popup de que ha recibido los olores del back, pero el mapa no los ha actualizado. (mapa)

**Comment by TomasTubertSFC** [comment]
![Captura de pantalla 2024-04-25 131324](https://github.com/ScienceForChange/odourCollect_2.0/assets/144031996/9e448f86-2490-43d5-b2a3-0125d9d663bc)
Hay algún valor que no está llegando.

**Comment by CarlosMillanSfC** [comment]
Ese undefined es normal?
![image](https://github.com/ScienceForChange/odourCollect_2.0/assets/144032932/4ef0cb89-154a-4bf0-ac1f-f207ea59ae27)
