### ISSUE TITLE
Error en geolocalización de usuario

### ISSUE THREAD

**Issue by almenarasfc** [ScienceForChange/odourCollect_2.0#312]
Cuando le das al icono de “localizacón” en el mapa, no se como llamarlo, la chincheta esa arriba a la derecha encima del interrogante
Hace un zoom out que se ve desde Barcelona a Sabadell, no debería ser al revés, un zoom in a donde estas tu localizado?

**Comment by TomasTubertSFC** [comment]
El control no se ejecuta solo, ha de ser que el usuario le clique. 
- ¿Qué pasa si la última localización es de hace + 5min? Podría significar que ya no estoy en ese lugar.
- ¿Qué pasa si el accuracy es más de 10 ? Podría significar que o estoy con un ordenador o con wifi o que he perdido señal gps.

Podría tener por detrás el watchPosition() y para tener en el servicio la localización y a su vez tener el control en el mapa para enseñar mi localización.
Tendría entonces, que crear algún error para las preguntas de arriba.
