### ISSUE TITLE
Corregir escala de Intensidad

### ISSUE THREAD

**Issue by JohanaSfC** [ScienceForChange/odourCollect_2.0#331]
@CarlosMillanSfC @TomasTubertSFC @almenarasfc @SysAdminSfC 

De acuerdo a la última reunión con Rosa, se debe cambiar las escalas del tono hedónico y la intensidad en la nueva app. Pero he comprobado que en el Figma la escala de intensidad están bien, coloco un pantallazo. 

<img width="200" alt="image" src="https://github.com/ScienceForChange/odourCollect_2.0/assets/83076037/09bbe755-dbe1-4609-9675-31d21a23f920">

Me pueden confirmar de donde se tomaron las escalas actuales de la nueva app: (Imperceptible, Muy débil, Débil, Indiferente, Fuerte, Muy fuerte, Extremadamente fuerte).

Hagan los cambios en la escala con la información del Figma, se debe cambiar las tres primeras escalas: imperceptible, muy débil y débil.

**Comment by CarlosMillanSfC** [comment]
duplicated at #332
